In [1]:
import torch
torch.__version__

'2.2.0+cpu'

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim #рзмерность

0

In [4]:
scalar.item() #только для тензоров с 1 элементом


7

In [5]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
matrix = torch.tensor([[7, 8],
                       [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
matrix.ndim

2

In [10]:
matrix.shape

torch.Size([2, 2])

In [11]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
TENSOR.shape

torch.Size([1, 3, 3])

In [13]:
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.3401, 0.0370, 0.2671, 0.2409],
         [0.8884, 0.1164, 0.1133, 0.4465],
         [0.2172, 0.9847, 0.9937, 0.3206]]),
 torch.float32)

In [14]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [15]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [16]:
zero_to_ten = torch.arange(0, 10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)# if True, operations performed on the tensor are recorded
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [19]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)
float_16_tensor.dtype

torch.float16

In [20]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.6375, 0.4510, 0.3147, 0.0730],
        [0.9710, 0.3142, 0.2931, 0.4803],
        [0.3941, 0.7276, 0.7626, 0.1813]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [21]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [22]:
tensor * 10

tensor([10, 20, 30])

In [23]:
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [24]:
tensor * tensor

tensor([1, 4, 9])

In [25]:
torch.matmul(tensor, tensor) #[1*1 + 2*2 + 3*3] = [14]

tensor(14)

In [26]:
tensor @ tensor

tensor(14)

In [27]:
%%time
# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: total: 15.6 ms
Wall time: 1.95 ms


tensor(14)

In [28]:
%%time
torch.matmul(tensor+1, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(20)

In [29]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [ ]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [ ]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [ ]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [ ]:
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=2,
                         out_features=6)
X = tensor_A
output = linear(X)
print(X.shape)
print(output.shape)
print(output)

torch.Size([3, 2])
torch.Size([3, 6])
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)


In [ ]:
x =torch.arange(0, 100, 10, dtype=torch.float32)
x

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [ ]:
print(x.max())
print(x.min())
print(x.mean())
print(x.sum())

tensor(90.)
tensor(0.)
tensor(45.)
tensor(450.)


In [ ]:
x =torch.arange(0, 100, 10)

In [ ]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

In [ ]:
print(x.argmax())
print(x.argmin())

tensor(9)
tensor(0)


In [ ]:
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [ ]:
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [ ]:
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [ ]:
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [ ]:
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

If you just want to reshape tensors, use torch.reshape. If you're also concerned about memory usage and want to ensure that the two tensors share the same data, use torch.view.

In [ ]:
z[:, 0] = 5
x

tensor([5., 2., 3., 4., 5., 6., 7.])

In [ ]:
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [ ]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [ ]:
x_stacked.T

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [ ]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [41]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")
#изменяя x_permuted изменится и x_original

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [31]:
x_original

tensor([[[0.5526, 0.7573, 0.6200],
         [0.6071, 0.3491, 0.7672],
         [0.5819, 0.4371, 0.1843],
         ...,
         [0.5548, 0.5820, 0.8081],
         [0.1509, 0.0269, 0.6388],
         [0.0151, 0.1588, 0.8572]],

        [[0.2604, 0.0127, 0.0251],
         [0.3765, 0.6442, 0.4273],
         [0.7034, 0.9630, 0.8969],
         ...,
         [0.2946, 0.8854, 0.4860],
         [0.9928, 0.1191, 0.2022],
         [0.5768, 0.1785, 0.0680]],

        [[0.4257, 0.9104, 0.5757],
         [0.7215, 0.3936, 0.2165],
         [0.0866, 0.4717, 0.4814],
         ...,
         [0.9840, 0.4366, 0.0422],
         [0.9703, 0.1747, 0.0369],
         [0.3069, 0.7095, 0.4167]],

        ...,

        [[0.0313, 0.0080, 0.0540],
         [0.7462, 0.5199, 0.9093],
         [0.4862, 0.0871, 0.4534],
         ...,
         [0.2206, 0.6133, 0.9233],
         [0.5523, 0.9997, 0.3466],
         [0.3419, 0.0363, 0.4807]],

        [[0.4124, 0.5592, 0.7068],
         [0.2325, 0.7590, 0.6440],
         [0.

In [32]:
x_permuted

tensor([[[0.5526, 0.6071, 0.5819,  ..., 0.5548, 0.1509, 0.0151],
         [0.2604, 0.3765, 0.7034,  ..., 0.2946, 0.9928, 0.5768],
         [0.4257, 0.7215, 0.0866,  ..., 0.9840, 0.9703, 0.3069],
         ...,
         [0.0313, 0.7462, 0.4862,  ..., 0.2206, 0.5523, 0.3419],
         [0.4124, 0.2325, 0.4375,  ..., 0.9275, 0.6048, 0.8293],
         [0.3327, 0.2777, 0.8949,  ..., 0.8337, 0.0254, 0.0510]],

        [[0.7573, 0.3491, 0.4371,  ..., 0.5820, 0.0269, 0.1588],
         [0.0127, 0.6442, 0.9630,  ..., 0.8854, 0.1191, 0.1785],
         [0.9104, 0.3936, 0.4717,  ..., 0.4366, 0.1747, 0.7095],
         ...,
         [0.0080, 0.5199, 0.0871,  ..., 0.6133, 0.9997, 0.0363],
         [0.5592, 0.7590, 0.6886,  ..., 0.1954, 0.6680, 0.9507],
         [0.1256, 0.1808, 0.3676,  ..., 0.7716, 0.6166, 0.5048]],

        [[0.6200, 0.7672, 0.1843,  ..., 0.8081, 0.6388, 0.8572],
         [0.0251, 0.4273, 0.8969,  ..., 0.4860, 0.2022, 0.0680],
         [0.5757, 0.2165, 0.4814,  ..., 0.0422, 0.0369, 0.

In [33]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [34]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [35]:
x[0][0]

tensor([1, 2, 3])

In [36]:
x[0][0][0]

tensor(1)

In [37]:
x[:,0]

tensor([[1, 2, 3]])

In [38]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [39]:
x[:, 1, 1]

tensor([5])


    torch.from_numpy(ndarray) - NumPy array -> PyTorch tensor.
    torch.Tensor.numpy() - PyTorch tensor -> NumPy array.


In [40]:
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [43]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [44]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.9718, 0.0552, 0.7485, 0.2791],
        [0.6949, 0.3332, 0.3847, 0.1216],
        [0.0734, 0.2335, 0.7925, 0.1093]])

Tensor B:
tensor([[0.7400, 0.3164, 0.2285, 0.6016],
        [0.8227, 0.2329, 0.1763, 0.5698],
        [0.3804, 0.0146, 0.8485, 0.7142]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [45]:
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED) 
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])